In [36]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [37]:
import numpy as np

#### Creating Arrays

In [38]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [39]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [40]:
np.array(a)

array([1. , 2. , 3.5])

In [41]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [42]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

#### Array Generation Functions

In [43]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [44]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [45]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [46]:
arr = np.linspace(1,10,5)
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Random Generation Functions

In [47]:
arr = np.random.rand(10)
arr

array([0.42838499, 0.88217157, 0.23883778, 0.21853341, 0.21179887,
       0.709406  , 0.61417163, 0.38554911, 0.79792432, 0.74017634])

In [48]:
arr = np.random.randn(10)
arr

array([-0.50971085, -1.5907703 ,  0.77847922, -2.02853272, -2.18850513,
       -1.36874717, -0.02812213,  0.10618183,  0.84646841,  1.84442682])

In [49]:
arr = np.random.randint(10,20,10)
arr

array([11, 11, 17, 18, 18, 10, 18, 10, 18, 13], dtype=int32)

### Array Attributes

In [50]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.shape

(3, 3)

In [52]:
arr.size

9

In [53]:
arr.dtype

dtype('int64')

### Array Methods

In [54]:
arr.min()

np.int64(1)

In [55]:
arr.max()

np.int64(9)

In [56]:
arr.sum()

np.int64(45)

In [57]:
np.sum(arr,axis=0) # column wise sum


array([12, 15, 18])

In [59]:
np.sum(arr,axis=1) # row wise sum

array([ 6, 15, 24])

In [60]:
arr.mean(0)

array([4., 5., 6.])

In [61]:
arr.std()

np.float64(2.581988897471611)

In [62]:
arr.argmax()

np.int64(8)

In [63]:
arr.argmin()

np.int64(0)

### Reshaping and Resizing

In [64]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])